version: '3.8'

services:
  # Signaling server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: voice-chat-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    volumes:
      - ./server/config:/app/config
    networks:
      - voice-chat-network

  # Client web app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_SERVER_URL=http://10.0.0.180:3001
        - REACT_APP_WS_URL=ws://10.0.0.180:3001
    container_name: voice-chat-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - voice-chat-network

networks:
  voice-chat-network:
    driver: bridge
